services:
  app:
    image: spark-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - ./shared-volume:/app/data
    networks:
      - spark-network

networks:
  spark-network:
    external: true
